### PR TITLE
Rewrite, code reorganization

### PR DESCRIPTION
**Pull request by l7ssha**
- [x] framework divided into modules
- [x] NNBD support [WIP]
- [ ] compatibility with latest sdk
- [x] #55 
  * [x] #58 
- [x] #52 
- [x] #47
- [x] #44
- [x] #35
- [x] #59
- [x] #60
- [x] #61
- [x] #62 
- [x] #64 
- [ ] #66
- [x] #67
- [x] #68
- [x] #69
  * [x] #70
- [x] #72 
- [x] #73

### CODE REVIEW

**Comment by l7ssha** [comment]
Fixed #47 in 56d048b

**Comment by l7ssha** [comment]
Fixed #52 in a681d0d

**Comment by l7ssha** [comment]
#70 fixed in 33e6bd1

**Comment by l7ssha** [comment]
#72 fixed in 1e4a14e

**Comment by tenhobi** [comment]
NNBD is now in tech preview https://twitter.com/dart_lang/status/1270749141790908417 👏

**Pull request merged**
